sudo: true
language: scala
before_install:
 # Initilize xvfb
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 # Instal google-chrome
 - export CHROME_BIN=/usr/bin/google-chrome
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 # Install Selenium chromedriver
 - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
 - unzip chromedriver_linux64.zip -d selenium-bin
 - export PATH=$PWD/selenium-bin:$PATH
before_script:
  - python -m SimpleHTTPServer 8080 &
script:
  - sbt ++$TRAVIS_SCALA_VERSION seleniumJSEnv/scalastyle seleniumJSEnv/test:scalastyle seleniumJSEnvTest/scalastyle seleniumJSHttpEnvTest/test:scalastyle seleniumJSEnvTest/test:scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION seleniumJSEnv/mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION seleniumJSEnvTest/run seleniumJSEnvTest/test seleniumJSHttpEnvTest/test 'set scalaJSStage in Global := FullOptStage' seleniumJSEnvTest/run seleniumJSEnvTest/test seleniumJSHttpEnvTest/test
  - sbt ++$TRAVIS_SCALA_VERSION 'set inScope(ThisScope in seleniumJSEnvTest)(jsEnv := new org.scalajs.jsenv.selenium.SeleniumJSEnv(org.scalajs.jsenv.selenium.Chrome))' seleniumJSEnvTest/run seleniumJSEnvTest/test seleniumJSHttpEnvTest/test 'set scalaJSStage in Global := FullOptStage' seleniumJSEnvTest/run seleniumJSEnvTest/test seleniumJSHttpEnvTest/test
  - sbt ++$TRAVIS_SCALA_VERSION 'set inScope(ThisScope in seleniumJSEnvTest)(jsEnv := new org.scalajs.jsenv.selenium.SeleniumJSEnv(org.scalajs.jsenv.selenium.Firefox).withKeepAlive())' seleniumJSEnvTest/run seleniumJSEnvTest/test seleniumJSHttpEnvTest/test 'set scalaJSStage in Global := FullOptStage' seleniumJSEnvTest/run seleniumJSEnvTest/test seleniumJSHttpEnvTest/test
  - sbt ++$TRAVIS_SCALA_VERSION 'set inScope(ThisScope in seleniumJSEnvTest)(jsEnv := new org.scalajs.jsenv.selenium.SeleniumJSEnv(org.scalajs.jsenv.selenium.Chrome).withKeepAlive())' seleniumJSEnvTest/run seleniumJSEnvTest/test seleniumJSHttpEnvTest/test 'set scalaJSStage in Global := FullOptStage' seleniumJSEnvTest/run seleniumJSEnvTest/test seleniumJSHttpEnvTest/test
scala:
  - 2.10.6
  - 2.11.7
  - 2.12.0-M3
jdk:
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
    - scala: 2.12.0-M3
      jdk: oraclejdk7
addons:
  firefox: latest
